# This is a sample docker-compose file, Please follow the naming convention for the service and container name, all node
# names must begin with "Node" followed by their sequence number. For a three node cluster your service/container names
# should be Node1, Node2 and Node3 as shown below(for service names they will be lowercase). You can add additional
# parameters and configurations as required by your implementation.



version: '3.7'

networks:
  application_network:

services:
  node1:                             
    image: raft                 # Same image name for 5 containers
    container_name: Node1       # Container names as per instructions
    build: Node/.
    volumes:
      - ./nodeinfo1:/data/info  # volumes to persist node information and also to store saved logs
    ports:
      - 8095:8080               # Exposed port to access UI
    environment:
      - CANDIDATE_ID=Node1      # Environment variable to identify nodes
      - CANDIDATE_KEY=0         
    networks:
      - application_network     # Same application network for all the containers
  
  node2:                          
    image: raft                 
    container_name: Node2
    build: Node/.
    volumes:
      - ./nodeinfo2:/data/info 
    ports:
      - 8096:8080                 
    environment:
      - CANDIDATE_ID=Node2
      - CANDIDATE_KEY=1         
    networks:
      - application_network
      
  node3:                           
    image: raft                 
    container_name: Node3
    build: Node/.
    volumes:
      - ./nodeinfo3:/data/info 
    ports:
      - 8097:8080                   
    environment:
      - CANDIDATE_ID=Node3
      - CANDIDATE_KEY=2         
    networks:
      - application_network
   
  node4:                             
    image: raft                 
    container_name: Node4
    build: Node/.
    volumes:
      - ./nodeinfo4:/data/info 
    ports:
      - 8098:8080                  
    environment:
      - CANDIDATE_ID=Node4
      - CANDIDATE_KEY=3         
    networks:
      - application_network
      
      
  node5:                             
    image: raft                 
    container_name: Node5
    build: Node/.
    volumes:
      - ./nodeinfo5:/data/info 
    ports:
      - 8099:8080                   
    environment:
      - CANDIDATE_ID=Node5
      - CANDIDATE_KEY=4        
    networks:
      - application_network
      
  controller:
     container_name: Controller
     build: TestUnit_Controller/.
     stdin_open: true
     networks:
      - application_network